DataSet:
  img_root: "..\\OPC_CT_Labelling"
  xml_paths: "..\\OPC_CT_Labelling\\annotations"
  labels: ["crack", "pore"]
  thickness: 2
  transform:
    flip: True
    crop: [1024, 1024]
  batch_size: 8

Model:
  model_name: deeplabv3_resnet50
  predefined: True
  lr: 0.001

Trainer:
  loss_fn: focal
  reduction: mean
  device: cuda
  epochs: 100
  eval_per_epoch: 10
  save_per_epoch: 10
  tensorboard: True
  save_path: ../models